# Generated by Django 6.0.5 on 2026-07-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('JOB_SEEKER', 'JOB_SEEKER'), ('RECRUITER', 'RECRUITER')], default='JOB_SEEKER', max_length=20),
        ),
    ]
