# Generated by Django 6.0.5 on 2026-07-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('JOB_SEEKER', 'JOB_SEEKER'), ('RECRUITER', 'RECRUITER')], default='JOB_SEEKER', max_length=20),
        ),
    ]
