# Generated by Django 6.0.7 on 2026-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
    ]
