# Generated by Django 6.0.7 on 2026-08-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_recruiterprofile_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_website',
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies_logos/')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51-200', '21-200 Employees'), ('201-500', '201-500 Employees'), ('501-1000', '501-1000 Employees'), ('1000+', '1000+ Employees')], max_length=20)),
                ('about', models.TextField(blank=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
